#print("my name is "+"ashirbad"+"and roll number is",20)
a="a"
b="b"
c="c"
d="d"
e="e"
f="f"
g="g"
h="h"
i="i"
j="j";k="k";l="l";m="m";n="n";o="o";p="p";q="q";
r="r";s="s";t="t";u="u";v="v";w="w";x="x";y="y";z="z"
print(ord(a))
print(ord(b))
print(ord(c))
print(ord(d))
print(ord(e))
print(ord(f))
print(ord(g))
print(ord(h))
print(ord(i))
print(ord(j))
print(ord(k))
print(ord(l))
print(ord(m))
print(ord(n))
print(ord(o))
print(ord(p))
print(ord(q))
print(ord(r))
print(ord(s))
print(ord(t))
print(ord(u))
print(ord(v))
print(ord(w))
print(ord(x))
print(ord(y,))
print(ord(z))
#print(ord(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z))
   #invalid format